services:
  tg_group_observer:
    build:
      context: .
    environment:
      ENVIRONMENT: 'TEST'
    volumes:
      - './:/usr/src/app'
      - './logs/:/var/log/'
    depends_on:
      - mongo
    entrypoint: /bin/sh /usr/src/app/entrypoint.sh
    ports:
      - "5000:5000"

  mongo:
      build:
        context: ./scripts/mongo
      restart: always
      environment:
        MONGO_INITDB_USERNAME: test
        MONGO_INITDB_PASSWORD: test
        MONGO_INITDB_DATABASE: db_group_observer
        MONGO_REPL_HOSTNAME: mongo  # should be the same as service name
        MONGO_REPL_ID: rs0  # should be the same as '--replSet' command arg
      expose:
        - "27017"
      ports:
        - "27017:27017"
      command: ["--replSet", "rs0"]
