services:
  tg_group_observer:
    build:
      context: .
    env_file: '.env'
    volumes:
      - './:/usr/src/app'
      - './logs/:/var/log/'
    depends_on:
      - mongo
    entrypoint: /bin/sh /usr/src/app/entrypoint.sh
    ports:
      - "5000:5000"

  mongo:
      image: mongo:8.0.0-rc13
      volumes:
        - './.data/:/data/db'
        - './migrations/:/docker-entrypoint-initdb.d/'
      restart: always
      env_file: '.env'
      expose:
        - "27017"
      ports:
        - "27018:27017"
#      command: ["--replSet", "rs0"]
