APP_NAME: telegram_group_observer

INIT_LOGGING: true
DEBUG: true
LOG_LEVEL: DEBUG

TG_API_TOKEN: ''

DB_NAME: db_group_observer
DB_LOGIN:
DB_PASSWORD:
DB_HOST: localhost
DB_PORT: 54321
DB_SCHEMA: public
DB_POOL_SIZE: 5
WEBHOOK_URL: https://localhost/
